/**
 * Turning a `SkyGradient` into something three.js can put behind the scene.
 *
 * ---------------------------------------------------------------------------
 * WHY A DATA TEXTURE AND NOT A SHADER OR A CANVAS
 * ---------------------------------------------------------------------------
 * A canvas gradient needs a DOM, which puts the whole sky path out of reach of
 * a headless test. A shader dome needs a mesh, a material and a draw call, and
 * has to be kept out of the way of the camera's far plane. An equirectangular
 * `DataTexture` needs neither: two pixels wide, sixty-four tall, generated by
 * a loop of plain arithmetic, and three.js already knows how to wrap it around
 * the sky. The pixel generation is a pure function so the ramp itself is unit
 * tested with no renderer anywhere near it.
 *
 * ---------------------------------------------------------------------------
 * WHICH WAY IS UP
 * ---------------------------------------------------------------------------
 * three.js maps an equirectangular background with `v = asin(dir.y)/PI + 0.5`,
 * so `v = 1` is the zenith. A `DataTexture` does not flip (`flipY` is false),
 * meaning `v = 1` samples the LAST row in memory. So the rows here run from
 * the NADIR upwards and `bottom` is written first. Getting this backwards
 * produces a sky that looks plausible in a screenshot and wrong on a headset,
 * which is exactly the class of bug the pure function exists to pin.
 */
import { DataTexture, EquirectangularReflectionMapping, LinearFilter, RGBAFormat, SRGBColorSpace } from "three";
import type { SkyGradient } from "@realitycollective/webxr-environment";
import { clamp01, lerp } from "@realitycollective/webxr-environment";

/** Columns in the generated texture. Two, because a 1px-wide equirect filters badly. */
export const SKY_TEXTURE_WIDTH = 2;

/** Default rows. Sixty-four is smooth to the eye and 512 bytes of texture. */
export const SKY_TEXTURE_HEIGHT = 64;

/**
 * The blend weight for `bottom` -> `top` at a given height up the sphere.
 *
 * `horizon` slides where the two colours meet and `exponent` shapes the ramp
 * on each side of it, so a sunset can hold its orange near the ground and lose
 * it quickly above.
 */
export function skyMix(gradient: SkyGradient, height: number): number {
  const horizon = clamp01(gradient.horizon ?? 0.5);
  const exponent = gradient.exponent ?? 1;
  const t = clamp01(height);
  // Below the horizon the ramp runs bottom -> midpoint, above it midpoint ->
  // top. A horizon at exactly 0 is the one division by zero possible here (it
  // can only be reached with t = 0 too), and its answer is the midpoint, since
  // that is by definition the colour AT the horizon. A horizon at 1 needs no
  // guard: `t` is clamped to 1, so the second branch is unreachable.
  const normalised =
    t <= horizon
      ? horizon <= 0
        ? 0.5
        : (t / horizon) * 0.5
      : 0.5 + ((t - horizon) / (1 - horizon)) * 0.5;
  return exponent === 1 ? normalised : Math.pow(normalised, exponent);
}

/**
 * RGBA bytes for the gradient, nadir row first. Pure - no three.js, no DOM.
 */
export function gradientPixels(gradient: SkyGradient, height = SKY_TEXTURE_HEIGHT): Uint8Array {
  const pixels = new Uint8Array(SKY_TEXTURE_WIDTH * height * 4);
  for (let row = 0; row < height; row += 1) {
    // Sample at the centre of the row, so the extreme rows are not pure
    // `bottom` / `top` and the ramp stays symmetric.
    const t = skyMix(gradient, (row + 0.5) / height);
    const r = Math.round(clamp01(lerp(gradient.bottom[0], gradient.top[0], t)) * 255);
    const g = Math.round(clamp01(lerp(gradient.bottom[1], gradient.top[1], t)) * 255);
    const b = Math.round(clamp01(lerp(gradient.bottom[2], gradient.top[2], t)) * 255);
    for (let column = 0; column < SKY_TEXTURE_WIDTH; column += 1) {
      const offset = (row * SKY_TEXTURE_WIDTH + column) * 4;
      pixels[offset] = r;
      pixels[offset + 1] = g;
      pixels[offset + 2] = b;
      pixels[offset + 3] = 255;
    }
  }
  return pixels;
}

/** Build the equirectangular background texture for a gradient sky. */
export function createSkyTexture(gradient: SkyGradient, height = SKY_TEXTURE_HEIGHT): DataTexture {
  const texture = new DataTexture(
    gradientPixels(gradient, height),
    SKY_TEXTURE_WIDTH,
    height,
    RGBAFormat,
  );
  texture.mapping = EquirectangularReflectionMapping;
  texture.colorSpace = SRGBColorSpace;
  texture.minFilter = LinearFilter;
  texture.magFilter = LinearFilter;
  texture.needsUpdate = true;
  return texture;
}
