/**
 * Turning a `SkyGradient` into something three.js can put behind the scene.
 *
 * ---------------------------------------------------------------------------
 * WHY A DATA TEXTURE AND NOT A SHADER OR A CANVAS
 * ---------------------------------------------------------------------------
 * A canvas gradient needs a DOM, which puts the whole sky path out of reach of
 * a headless test. A shader dome needs a mesh, a material and a draw call, and
 * has to be kept out of the way of the camera's far plane. An equirectangular
 * `DataTexture` needs neither: two pixels wide, sixty-four tall, generated by
 * a loop of plain arithmetic, and three.js already knows how to wrap it around
 * the sky. The pixel generation is a pure function so the ramp itself is unit
 * tested with no renderer anywhere near it.
 *
 * ---------------------------------------------------------------------------
 * WHICH WAY IS UP
 * ---------------------------------------------------------------------------
 * three.js maps an equirectangular background with `v = asin(dir.y)/PI + 0.5`,
 * so `v = 1` is the zenith. A `DataTexture` does not flip (`flipY` is false),
 * meaning `v = 1` samples the LAST row in memory. So the rows here run from
 * the NADIR upwards and `bottom` is written first. Getting this backwards
 * produces a sky that looks plausible in a screenshot and wrong on a headset,
 * which is exactly the class of bug the pure function exists to pin.
 */
import { DataTexture, EquirectangularReflectionMapping, LinearFilter, RGBAFormat, SRGBColorSpace } from "three";
import type { IblGradient, Rgb, SkyGradient } from "@realitycollective/webxr-environment";
import { clamp01, lerp } from "@realitycollective/webxr-environment";

/**
 * A gradient with or without a horizon stop, from either slot.
 *
 * The sky and the environment map take the same colours and differ only in
 * what they are hung on, so one generator serves both. `horizon` and
 * `exponent` shape the sky's ramp and have no meaning for an environment map,
 * which is why they are optional here rather than duplicated.
 */
export type RampGradient = SkyGradient | IblGradient;

/** Columns in the generated texture. Two, because a 1px-wide equirect filters badly. */
export const SKY_TEXTURE_WIDTH = 2;

/** Default rows. Sixty-four is smooth to the eye and 512 bytes of texture. */
export const SKY_TEXTURE_HEIGHT = 64;

/**
 * The blend weight for `bottom` -> `top` at a given height up the sphere.
 *
 * `horizon` slides where the two colours meet and `exponent` shapes the ramp
 * on each side of it, so a sunset can hold its orange near the ground and lose
 * it quickly above.
 */
export function skyMix(gradient: RampGradient, height: number): number {
  const horizon = clamp01(("horizon" in gradient ? gradient.horizon : undefined) ?? 0.5);
  const exponent = ("exponent" in gradient ? gradient.exponent : undefined) ?? 1;
  const t = clamp01(height);
  // Below the horizon the ramp runs bottom -> midpoint, above it midpoint ->
  // top. A horizon at exactly 0 is the one division by zero possible here (it
  // can only be reached with t = 0 too), and its answer is the midpoint, since
  // that is by definition the colour AT the horizon. A horizon at 1 needs no
  // guard: `t` is clamped to 1, so the second branch is unreachable.
  const normalised =
    t <= horizon
      ? horizon <= 0
        ? 0.5
        : (t / horizon) * 0.5
      : 0.5 + ((t - horizon) / (1 - horizon)) * 0.5;
  return exponent === 1 ? normalised : Math.pow(normalised, exponent);
}

/**
 * The colour at a height up the sphere.
 *
 * `intensity` is NOT applied here. three.js has `backgroundIntensity` and
 * `environmentIntensity` on the scene, and multiplying bytes in an 8-bit
 * texture would clip everything brighter than white while the scene property
 * does the same job in floating point.
 *
 * With no `equator` this is the two-stop ramp the package started with. With
 * one it is two ramps meeting at the horizon, which is what IWSDK's dome has
 * always been and what an app needs to put a bright band at eye level. The
 * `exponent` shaping applies to the position within whichever half we are in,
 * so a sunset can hold its colour near the ground on both engines.
 */
export function gradientColourAt(gradient: RampGradient, height: number): Rgb {
  const equator = gradient.equator;
  if (equator === undefined) {
    const t = skyMix(gradient, height);
    return [
      lerp(gradient.bottom[0], gradient.top[0], t),
      lerp(gradient.bottom[1], gradient.top[1], t),
      lerp(gradient.bottom[2], gradient.top[2], t),
    ];
  }
  const horizon = clamp01(("horizon" in gradient ? gradient.horizon : undefined) ?? 0.5);
  const t = clamp01(height);
  const exponent = ("exponent" in gradient ? gradient.exponent : undefined) ?? 1;
  const below = t <= horizon;
  // At a horizon of 0 every sample is at or above it, so the division below is
  // never reached with a zero denominator; the same holds at 1 for the other
  // half, because `t` is clamped.
  const raw = below ? (horizon <= 0 ? 1 : t / horizon) : (t - horizon) / (1 - horizon);
  const local = exponent === 1 ? raw : Math.pow(raw, exponent);
  const from = below ? gradient.bottom : equator;
  const to = below ? equator : gradient.top;
  return [lerp(from[0], to[0], local), lerp(from[1], to[1], local), lerp(from[2], to[2], local)];
}

/**
 * RGBA bytes for the gradient, nadir row first. Pure - no three.js, no DOM.
 */
export function gradientPixels(gradient: RampGradient, height = SKY_TEXTURE_HEIGHT): Uint8Array {
  const pixels = new Uint8Array(SKY_TEXTURE_WIDTH * height * 4);
  for (let row = 0; row < height; row += 1) {
    // Sample at the centre of the row, so the extreme rows are not pure
    // `bottom` / `top` and the ramp stays symmetric.
    const colour = gradientColourAt(gradient, (row + 0.5) / height);
    const r = Math.round(clamp01(colour[0]) * 255);
    const g = Math.round(clamp01(colour[1]) * 255);
    const b = Math.round(clamp01(colour[2]) * 255);
    for (let column = 0; column < SKY_TEXTURE_WIDTH; column += 1) {
      const offset = (row * SKY_TEXTURE_WIDTH + column) * 4;
      pixels[offset] = r;
      pixels[offset + 1] = g;
      pixels[offset + 2] = b;
      pixels[offset + 3] = 255;
    }
  }
  return pixels;
}

/** Build the equirectangular background texture for a gradient sky. */
export function createSkyTexture(gradient: RampGradient, height = SKY_TEXTURE_HEIGHT): DataTexture {
  const texture = new DataTexture(
    gradientPixels(gradient, height),
    SKY_TEXTURE_WIDTH,
    height,
    RGBAFormat,
  );
  texture.mapping = EquirectangularReflectionMapping;
  texture.colorSpace = SRGBColorSpace;
  texture.minFilter = LinearFilter;
  texture.magFilter = LinearFilter;
  texture.needsUpdate = true;
  return texture;
}
